### ISSUE TITLE
`Error: No node found for selector: a[href="/sign_in"` occurs

### ISSUE THREAD

**Issue by master-q** [tekiomo/mf-auto-updater#8]
```
$ date
Fri 02 Oct 2020 08:26:51 AM JST
yarn run v1.21.1
$ yarn fetch
node index.js
(node:374418) UnhandledPromiseRejectionWarning: Error: No node found for selector: a[href="/sign_in"]
    at assert (/home/kiwamu/src/mf-all-updater/node_modules/puppeteer/lib/helper.js:269:15)
    at DOMWorld.click (/home/kiwamu/src/mf-all-updater/node_modules/puppeteer/lib/DOMWorld.js:325:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/kiwamu/src/mf-all-updater/index.js:20:5)
    at async /home/kiwamu/src/mf-all-updater/index.js:83:10
  -- ASYNC --
    at Frame.<anonymous> (/home/kiwamu/src/mf-all-updater/node_modules/puppeteer/lib/helper.js:105:23)
    at Page.click (/home/kiwamu/src/mf-all-updater/node_modules/puppeteer/lib/Page.js:956:33)
    at main (/home/kiwamu/src/mf-all-updater/index.js:20:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/kiwamu/src/mf-all-updater/index.js:83:10
(node:374418) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise
 which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unha
ndled_rejections_mode). (rejection id: 1)
(node:374418) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero
 exit code.
```

**Comment by master-q** [comment]
Thanks. It's fixed.
